config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      post :otp
    end
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone_extension.rb
class PhoneExtension < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :blood_group, :phone, :phone_extension_id
  validates :phone, :presence => { :message => 'must be given please 10 digit phone number' }
  validates :phone, :numericality => true, :length => { is: 10, :message => 'Phone is the wrong length (Should be 10 digit)' }
  validates_presence_of :otp_no
  has_one_time_password column_name: :otp_no, length: 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You updated your details successfully."
      redirect_to otp_users_path(id: @user)
    else
      render 'new'
    end
  end

  def otp
    @user_otp_code = User.find( params['id'] )
    @user_otp_code.otp_code
    sleep 30
    params
  end

  private
  def user_params
    params.require(:user).permit(:name, :blood_group, :phone, :phone_extension_id  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helpalife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <%= link_to "New donor", new_user_path, class: "btn btn-primary btn-small"  %>
    </div>
  </div>
</div>
<% @users.each do |user| %>
  <br>
    Name :&nbsp;<%= user.name %> <br>
    Blood group :&nbsp;<%= user.blood_group %> <br>
    Phone number :&nbsp; <%= user.phone %> <br>
<% end %>

app/views/users/new.html.erb
<div class="container margin-top-10-percent">
  <div class="card">
    <div class="card-header"><b> Step 1 </b></div>
      <div class="card-body" >
        <%= simple_form_for @user, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
          <%= f.input :name, :required => true, :placeholder=> "Full name" %>
          <%= f.input :phone_extension_id, collection: PhoneExtension.all, value_method: :id, label_method: :code,
                      :prompt => "- Select country code -", :required => true %>
          <%= f.input :phone, :placeholder=> "Phone number", :required => true
                     %>
          <%= f.input :blood_group, collection: [["A1+", "A1+"],["A1-", "A1-"], ["A2+", "A2+"],["A2-", "A2-"],
                                                 ["B+", "B+"],["B-", "B-"],["A1B+", "A1B+"],["A1B-", "A1B-"],
                                                 ["A2B+", "A2B+"],["A2B-", "A2B-"],["AB+", "AB+"],
                                                 ["AB-", "AB-"],["O+", "O+"],["O-", "O-"],["A+", "A+"],
                                                 ["A-", "A-"]], value: @user.blood_group,
                      include_blank: "- Choose blood group -" %>
          <%= f.button :submit, "Continue", :class => 'btn btn-primary' %>
          <%= link_to "Cancel donor", :back, :class => 'btn btn-default' %>
          <% end %>
     </div>
   </div>
  </div>
</div>

app/views/users/otp.html.erb
<div class="container">
  <!--  <div class='row'>-->
  <div class="col-md-6">
    <div class="panel panel-danger">
      <div class="panel-heading"><b> Step 2 </b></div>
      <div class="panel-body" >
        <%= simple_form_for @user_otp_code do |f| %>
          <div class="form-group">
            <%= f.label :otp_no, label: 'Enter OTP', class: "control-label" %>
            <%= f.input :otp_no, :placeholder=> "----", :required => true, input_html: { style:  "width: 50%;"},
                        label: false  %>
          </div>
          <div class="form-group">
            <%= f.button :submit, "Continue", :class => 'btn btn-primary' %>
            <%= link_to "Back to step 1", :back, :class => 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!--  </div>-->
</div>